# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d577a7db1ea6d3cdad61b3e5064f4990e640ced45421f8e0a2fd8484b14b23cfff0e5a6757e614513ab089b151c47ca84b40718e702bc3dccd4925f059d0570

test:
  secret_key_base: 24a28b15439e39275542b021e622fe66ba327a6ec9046471ca2ae07c963ea636ad68b1b72b2a84d42c3d54732e5300d3522a4526f10dcd174bf1b2fd5403f3c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
